name: Gitea Next Version Tag
description: Create the next version tag based on the latest tag
inputs:
  gitea-token:
    description: The Gitea token
    required: true
  last-version: 
    description: Provide a custom last version instead of fetching it from the tags
    required: false
  fallback:
    description: The fallback version used if none has been found, defaults to 0.0.0
    required: false
    default: 0.0.0
  prefix:
    description: The prefix used for version. defaults to v -> v1.2.0
    required: true
    default: v
  major-label:
    description: The label used to increment the major version, defaults to major
    required: false
    default: major
  minor-label:
    description: The label used to increment the minor version, defaults to minor
    required: false
    default: minor
  patch-label:
    description: The label used to increment the patch version, defaults to patch
    required: false
    default: patch
  ignore-label:
    description: The label used to ignore the version increment, defaults to no-version
    required: false
    default: no-version
outputs:
  next:
    description: The incremented version
  latest:
    description: The latest version
runs:
  using: node20
  main: dist/index.js
branding:
  color: purple
  icon: arrow-up-circle